name: PDBminer_env
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.78
  - matplotlib=3.2.2
  - networkx=2.8.4
  - numpy=1.21.2
  - pandas=1.2.4
  - python=3.8.8
  - requests=2.25.1
  - seaborn=0.12.0
  - yaml=0.2.5
