name: PDBminer_env
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.83
  - matplotlib=3.8.3
  - networkx=3.2.1
  - numpy=1.26.4
  - pandas=2.2.1
  - python=3.12.2
  - requests=2.31.0
  - seaborn=0.13.2
  - pyyaml=6.0.1

