name: PDBminer_env
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.83
  - matplotlib=3.8.2
  - networkx=3.2.1
  - numpy=1.26.0
  - pandas=2.1.3
  - python=3.10.12
  - requests=2.25.1
  - seaborn=0.13.0
  - pyyaml=5.4.1
